### ISSUE TITLE
Recursive directoryOpen not finding all files in nested MacOs directory

### ISSUE THREAD

**Issue by steveskimmel** [GoogleChromeLabs/browser-fs-access#139] opened 2023-03-06 12:14 UTC
The new File System Access API is not performing properly when processing large directories (500+ files) using the latest Chromium browsers on MacOs (110+). The same code performs properly on Chromium browsers (110+) on Windows. 

The following example yields different results:
```
const blobsInDirectory = await directoryOpen({
      recursive: true,
    });
```
On MacOs, the result consistently yields less than all the files in nested directories. On Windows, the result yields all of the files in nested directories. 

I'm trying to understand why this is the case, and what the solution is to properly access all the files in nested directories on all operating systems?

Thank you

**Comment by tomayac** [comment] 2023-03-06 12:25
Could it be due to different ways of dealing with hidden files? Windows saves different metadata files like image thumbnails etc. On macOS, the same happens with `.DS_Store` files. If, for example, you check the same USB pen first on Windows and then on macOS, the second OS will add metadata that was not yet there when you tested on the first.

**Comment by steveskimmel** [comment] 2023-03-06 12:35
I don't think that's the case. On prior Chromium versions (109 for example), file detection from within nested directories worked perfectly.

**Comment by tomayac** [comment] 2023-03-06 12:39
In this case, it sounds more like a Chrome bug. Could you please try to create a minimally reproducible test case and file a new Chromium bug via [new.crbug.com](https://new.crbug.com/). You can comment with the bug URL here, and I can help triaging. For now, I'm closing the issue, since it's not with the library apparently.

**Closed by tomayac** 2023-03-06 12:39 UTC

**Comment by steveskimmel** [comment] 2023-03-06 14:26
Thank you! https://bugs.chromium.org/p/chromium/issues/detail?id=1421735

**Comment by tomayac** [comment] 2023-03-06 14:51
Could you append screenshots that show how the same code delivers different results based on the operating system and the Chrome version? These should be the screenshots I expect:

- Chrome 109, Windows (shows 3,000 files)
- Chrome 109, macOS (shows 3,000 files)
- Chrome 110, Windows (does something different than 3,000 files, and/or something different than macOS)
- Chrome 110, macOS (shows something different than 3,000 files, and/or something different than Windows)

At present the issue doesn't mention the problem you describe in https://github.com/GoogleChromeLabs/browser-fs-access/issues/139#issuecomment-1456056717.

**Comment by steveskimmel** [comment] 2023-03-06 15:29
#Chrome 109
###MacOS
![Screenshot 2023-03-06 at 17 02 41](https://user-images.githubusercontent.com/13495789/223151634-18f569ba-7c54-49a8-83cd-b81e9e31adeb.png)
![Screenshot 2023-03-06 at 17 03 08](https://user-images.githubusercontent.com/13495789/223151660-2c859c89-2dcc-4df4-9411-c33bac41f1e1.png)
###Windows
![Capture](https://user-images.githubusercontent.com/13495789/223155047-f97dad98-9d45-4d70-8c83-b2bdc689c908.PNG)
![Capture1](https://user-images.githubusercontent.com/13495789/223155055-c4150582-1143-4050-8e7c-81be7d53f63c.PNG)
#Chrome 110
###MacOs
![Screenshot 2023-03-06 at 17 05 48](https://user-images.githubusercontent.com/13495789/223155155-83617cec-ae5a-4f15-a5f8-475da84c42e4.png)
![Screenshot 2023-03-06 at 17 05 05](https://user-images.githubusercontent.com/13495789/223155139-95d8ead3-df2b-405e-a994-7e1442bc8e9c.png)
###Windows
![Capture2](https://user-images.githubusercontent.com/13495789/223155208-72b74dc8-fb66-4b0a-a442-4892d8d00982.PNG)
![Capture4](https://user-images.githubusercontent.com/13495789/223155223-92ed32c5-d404-4c1d-9fcc-ff93cfa1e767.PNG)

**Comment by tomayac** [comment] 2023-03-06 15:32
(Sorry, I meant as attachments to the bug. Please use descriptive file names. Thanks a lot!

**Comment by steveskimmel** [comment] 2023-03-06 15:40
Cool, I've done that. Thanks.
