### ISSUE TITLE
cannot find name ‘FileSystemFileHandle.

### ISSUE THREAD

**Issue by aradhyakalva** [GoogleChromeLabs/browser-fs-access#121] opened 2022-07-19 02:47 UTC
"**Version used**
-"browser-fs-access":  "^0. 31.01
"ts-node": "~9.1. 11
"typescript":  "~4.3.5",
node v14.17.6
npm v6.14.15

**Issue**

Below error is showing up in logs while starting the application

Error: libs/node modules/browser-fs-access/index.d.ts:147:20 - error TS2304: Cannot find name 'FileSystemFileHandle'

existingHandle?: FilesystemFileHandle | null,

Error: libs/node modules/browser-fs-access/index.d.ts:157:30 - error TS2304: Cannot find name 'FilesystemFileHandle'

filePickershown?: (handle: FileSystemFileHandle | null) => void | null

Error: libs/node modules/browser-fs-access/index.d.ts:158:12 - error Is2304: cannot find name "FilesystemFileHandle"

 : Promise<FileSystemFileHandle I null>;

**Comment by tomayac** [comment] 2022-07-19 07:53
This seems to be caused by the same root issue as https://github.com/tldraw/tldraw/pull/660#issuecomment-1113170053. In this thread, @andarist was mentioned as potentially being able to help.

**Comment by Andarist** [comment] 2022-07-19 08:09
@tomayac I'm on vacation rn but I might take a look in a week when I get back. Don't hesitate to ping me again if I don't - sometimes things just slip through the cracks

**Comment by tomayac** [comment] 2022-07-19 08:15
Enjoy your vacation! If we find a fix for this, eventually tldraw could use the module as a direct dependency, rather than maintaining a local copy.

**Comment by Andarist** [comment] 2022-08-08 18:45
@aradhyakalva the most likely fix for your problem is to add this to your `tsconfig.json`::
```json
{
  "compilerOptions": { "lib": ["DOM"] }
}
```

**Comment by tomayac** [comment] 2022-08-22 12:29
This seems to be fixable as per the instructions given in the comment above.

**Closed by tomayac** 2022-08-22 12:29 UTC
